{% raw %}
server:
  alert:
    EtcdFailedTotalIn5m:
      if: >-
        sum by(method) (rate(etcd_http_failed_total{code!~"4[0-9]{2}"}[5m]))
        / sum by(method) (rate(etcd_http_received_total[5m])) > 0.01
      labels:
        severity: warning
        service: etcd
      annotations:
        summary: 'High number of HTTP requests are failing on etcd'
        description: '{{ $value }}% of requests for {{ $labels.method }} failed on etcd instance {{ $labels.instance }}'
{% endraw %}
